FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app
EXPOSE 80

# copy all .csproj files and restore as distinct layers.   Use of the same COPY command
# for every dockerfile in the project to take advantage of docker caching
COPY Carsites.sln Carsites.sln
COPY src/AuctionService/API/API.csproj src/AuctionService/API/API.csproj
COPY src/AuctionService/Application/Application.csproj src/AuctionService/Application/Application.csproj
COPY src/AuctionService/Domain/Domain.csproj src/AuctionService/Domain/Domain.csproj
COPY src/AuctionService/Infrastructure/Infrastructure.csproj src/AuctionService/Infrastructure/Infrastructure.csproj
COPY src/SearchService/SearchService.csproj src/SearchService/SearchService.csproj
COPY src/GatewayService/GatewayService.csproj src/GatewayService/GatewayService.csproj
COPY src/Contracts/Contracts.csproj src/Contracts/Contracts.csproj
COPY src/IdentityService/IdentityService.csproj src/IdentityService/IdentityService.csproj
COPY tests/AuctionService.FunctionalTests/AuctionService.FunctionalTests.csproj tests/AuctionService.FunctionalTests/AuctionService.FunctionalTests.csproj
COPY tests/AuctionService.IntegrationTests/AuctionService.IntegrationTests.csproj tests/AuctionService.IntegrationTests/AuctionService.IntegrationTests.csproj
COPY tests/AuctionService.UnitTests/AuctionService.UnitTests.csproj tests/AuctionService.UnitTests/AuctionService.UnitTests.csproj

# Restore package deps
RUN dotnet restore Carsites.sln

# Copy the app folders over
COPY src/SearchService src/SearchService
COPY src/Contracts src/Contracts
WORKDIR /app/src/SearchService
RUN dotnet publish -c Release -o /app/src/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/src/out .
ENTRYPOINT [ "dotnet", "SearchService.dll" ]